import{S as q,a as B,i as a}from"./assets/vendor-GN5hr8qZ.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function n(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=n(e);fetch(e.href,o)}})();const f=document.querySelector(".gallery"),m=document.querySelector(".loader"),y=document.querySelector(".load-btn");let M=new q(".gallery a",{captionsData:"alt",captionDelay:250});function h(r){const t=r.map(({webformatURL:n,largeImageURL:s,tags:e,likes:o,views:i,comments:v,downloads:S})=>`
      <li class="gallery-item">
        <a href="${s}">
          <img src="${n}" alt="${e}" width ="300" loading="lazy" />
        </a>
        <div class="info">
          <p><b>Likes:</b> ${o}</p>
          <p><b>Views:</b> ${i}</p>
          <p><b>Comments:</b> ${v}</p>
          <p><b>Downloads:</b> ${S}</p>
        </div>
      </li>
    `).join("");f.insertAdjacentHTML("beforeend",t),M.refresh()}function $(){f.innerHTML=""}function p(){m.classList.remove("hidden")}function g(){m.classList.add("hidden")}function b(){y.classList.remove("hidden")}function L(){y.classList.add("hidden")}function P(){const{height:r}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}const E="52352644-c897e22e6be43ef28cf6cdead",O="https://pixabay.com/api/";async function w(r,t=1,n=15){const s={key:E,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:n};return(await B.get(O,{params:s})).data}const u=document.querySelector(".form"),H=document.querySelector(".load-btn");let l="",c=1;const d=15;u.addEventListener("submit",async r=>{if(r.preventDefault(),l=r.currentTarget.elements.query.value.trim(),!l){a.warning({title:"Увага",message:"Введіть пошуковий запит!"});return}c=1,$(),L();try{p();const t=await w(l,c,d);if(t.hits.length===0){a.info({title:"Немає результатів",message:"Зображення за цим запитом не знайдено."});return}h(t.hits),t.totalHits>d&&b()}catch(t){a.error({title:"Помилка",message:"Не вдалося завантажити зображення."}),console.error(t)}finally{g(),u.reset()}});H.addEventListener("click",async()=>{c+=1,L();try{p();const r=await w(l,c,d);h(r.hits),P();const t=Math.ceil(r.totalHits/d);c<t?b():a.info({title:"Кінець результатів",message:"Were sorry, but you ve reached the end of search results"})}catch(r){a.error({title:"Помилка",message:"Не вдалося завантажити більше зображень."}),console.error(r)}finally{g()}});
//# sourceMappingURL=index.js.map
